### ISSUE TITLE
这个如何设置农历呀老哥

### ISSUE THREAD

**Issue by liuhaotian1122** [JionghaoSong/DailyMorning_Star#10]
# 生日1，修改名字为对应需要显示的名字，如果生日为农历，在最前面加上r即可
"birthday1": {"name": "dd", r"birthday": "1999-08-20"},

**Comment by JionghaoSong** [comment]
你试试
"birthday1": {"name": "dd", "birthday": r"1999-08-20"},

**Comment by JionghaoSong** [comment]
你试试
"birthday1": {"name": "dd", "birthday": r"1999-08-20"},
或者
"birthday1": {"name": "dd", "birthday": "r1999-08-20"},

成功了你在这里和我说一声再

**Comment by JionghaoSong** [comment]
我感觉应该是
"birthday1": {"name": "dd", "birthday": "r1999-08-20"},
