### ISSUE TITLE
出现了错误

### ISSUE THREAD

**Issue by Skylarrkuo** [JionghaoSong/DailyMorning_Star#11]
<img width="325" alt="1683271027249" src="https://user-images.githubusercontent.com/67224949/236397922-bb294c29-f69f-4aea-acc6-f41b5c26613b.png">
今天的运行状况变成了这样。。
测试发现只要在模板的参数前加上中文就可以正常显示，但是文字的颜色一直是失效的
这是git的问题还是微信那边出问题了？

**Comment by JionghaoSong** [comment]
收到反馈，我先简单看看原因是啥。
最近要毕业，问题大的话可能得月底🥺



---Original---
From: ***@***.***&gt;
Sent at: 2023年5月5日(Fri) PM3:19
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [JionghaoSong/DailyMorning_Star] 出现了错误 (Issue #11)




 

 今天的运行状况变成了这样。。 测试发现只要在模板的参数前加上中文就可以正常显示，但是文字的颜色一直是失效的 这是git的问题还是微信那边出问题了？

**Comment by JionghaoSong** [comment]
非常抱歉的通知大家，因为微信改版原因，以后无法发送自定义颜色的文字了。
更新如下：
2023年5月4日
1）去除自定义颜色、表情符号；（表情符号由替换为“□”改为直接去除）
2）去除尾部/备注内容；
3）去除首行内容。 

![image](https://user-images.githubusercontent.com/64049788/236500356-0f1aca76-55e3-411b-8262-9359908007c6.png)

**Comment by Ethan1X** [comment]
没有颜色比较bug，兄弟们有新的方法，及时share，互相促进一下哈

**Comment by JionghaoSong** [comment]
颜色这个微信官方不松口是肯定没法加的，现在能做的也就是把自定义的话加进去。
一个人的时间和精力确实有限，欢迎大家相互交流。
如果有好的我可以添加到contributor里

**Comment by liuhaotian1122** [comment]
为什么不显示各自的生日倒计时了
