### ISSUE TITLE
请大佬看看这是怎么回事呜呜

### ISSUE THREAD

**Issue by Cheryl-Chuzy** [JionghaoSong/DailyMorning_Star#14]
Run python3 main.py
  python[3](https://github.com/Cheryl-Chuzy/DailyMorning_Star/actions/runs/5031059807/jobs/9023889293#step:5:3) main.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.3/x6[4](https://github.com/Cheryl-Chuzy/DailyMorning_Star/actions/runs/5031059807/jobs/9023889293#step:5:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.3/x[6](https://github.com/Cheryl-Chuzy/DailyMorning_Star/actions/runs/5031059807/jobs/9023889293#step:5:6)4/lib
sh: 1: pause: not found
获取access_token失败，请检查app_id和app_secret是否正确
Error: Process completed with exit code 1.

**Comment by JionghaoSong** [comment]
请检查app_id和app_secret是否正确
就是那几个测试模板的号正不正确，有没有多余的空格或者分号



---Original---
From: ***@***.***&gt;
Sent at: 2023年5月20日(Sat) PM4:01
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [JionghaoSong/DailyMorning_Star] 请大佬看看这是怎么回事呜呜 (Issue #14)




 
Run python3 main.py
 python3 main.py
 shell: /usr/bin/bash -e {0}
 env:
 pythonLocation: /opt/hostedtoolcache/Python/3.11.3/x64
 LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib
 sh: 1: pause: not found
 获取access_token失败，请检查app_id和app_secret是否正确
 Error: Process completed with exit code 1.
