### ISSUE TITLE
linux 目录执行命令错误 

### ISSUE THREAD

**Issue by yuag** [JionghaoSong/DailyMorning_Star#16]
1. 定时任务
python3 /root/DailyMorning_Star-main/main.py
推送消息失败，请检查config.txt文件是否与程序位于同一路径

修复如下：
import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))

**Comment by JionghaoSong** [comment]
这个问题现在还存在吗？

**Comment by yuag** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
