### ISSUE TITLE
已解决--每日金句，汉语显示不全

### ISSUE THREAD

**Issue by Jeremy-stu** [JionghaoSong/DailyMorning_Star#17]
为何每日金句一超过两行就省略了，而英语可以

**Comment by JionghaoSong** [comment]
这两天我看一下哈

**Comment by JionghaoSong** [comment]
因为微信模板字数超过20字，剩下的会变成省略号。
我去看看应该怎么弄好点

**Comment by Jeremy-stu** [comment]
> 因为微信模板字数超过20字，剩下的会变成省略号。 我去看看应该怎么弄好点

那英文咋会自己换行呢，是不是按字符算的

**Comment by JionghaoSong** [comment]
我记得中文字符是英文的二倍吧，小时候发短信，英文可以 120 个字，汉子是 60 个



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jeremy-stu ***@***.***&gt;
发送时间: 2023年11月13日 18:22
收件人: JionghaoSong/DailyMorning_Star ***@***.***&gt;
抄送: Harry.Song ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [JionghaoSong/DailyMorning_Star] 每日金句，汉语显示不全 (Issue #17)

**Comment by Jeremy-stu** [comment]
> 我记得中文字符是英文的二倍吧，小时候发短信，英文可以 120 个字，汉子是 60 个 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Jeremy-stu ***@***.***&gt; 发送时间: 2023年11月13日 18:22 收件人: JionghaoSong/DailyMorning_Star ***@***.***&gt; 抄送: Harry.Song ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [JionghaoSong/DailyMorning_Star] 每日金句，汉语显示不全 (Issue #17)

是的，刚刚数了数英文三十多个字符，没超过四十个。感觉可以加一个自动判断汉字字数的函数，超过就自动换行

**Comment by JionghaoSong** [comment]
我修好了，重新换一下模板加上fork一下吧

**Comment by Jeremy-stu** [comment]
> 我修好了，重新换一下模板加上fork一下吧
忘记说了，英文其实也有超出不显的时候，不过情况几乎很少
![Screenshot_2023-11-13-19-59-28-384-edit_com.tencent.mm.jpg](https://github.com/JionghaoSong/DailyMorning_Star/assets/76563274/c4533967-df5e-4994-9043-2eca997a0bb5)

**Comment by JionghaoSong** [comment]
嗯 现在英文的也改了

**Comment by Jeremy-stu** [comment]
> > 嗯 现在英文的也改了
> 
> 可以了，感谢，不过有个疑问英文这里判断的是字符数还是什么？你给的是20，是不是有点小了，我给50发现还能进if，但是我数了英文字符数是小于50的
> ![Screenshot_2023-11-14-00-52-44-335-edit_com.github.android.jpg](https://github.com/JionghaoSong/DailyMorning_Star/assets/76563274/6e04431b-b913-4edb-8890-315014bf4289)
> 
> 

数错了英文字符数确实是大于50的,所以设置50也能进if，而且英文字符数都80个了还能显示，也不知道英文键值最大限制多少个英文字符

**Comment by JionghaoSong** [comment]
可以自己放一段话进去，看看最大字符是多少。
没记错的话，估计可能是 200 了


------------------ 原始邮件 ------------------
发件人: Jeremy-stu ***@***.***&gt;
发送时间: 2023年11月14日 11:32
收件人: harry.sjh ***@***.***&gt;
主题: Re: [JionghaoSong/DailyMorning_Star] 每日金句，汉语显示不全 (Issue #17)





   
嗯 现在英文的也改了
  
可以了，感谢，不过有个疑问英文这里判断的是字符数还是什么？你给的是20，是不是有点小了，我给50发现还能进if，但是我数了英文字符数是小于50的
 
  
数错了英文字符数确实是大于50的,所以设置50也能进if，而且英文字符数都80个了还能显示，也不知道英文键值最大限制多少个英文字符

**Comment by JionghaoSong** [comment]
https://kejiweixun.com/note/202303241915#20-%E4%B8%AA%E5%AD%97%E7%9A%84%E8%AE%A1%E7%AE%97%E6%96%B9%E6%B3%95
你可以看一下这个说的，虽然我感觉他也没太弄明白

**Comment by JionghaoSong** [comment]
GPT是这么理解的
![image](https://github.com/JionghaoSong/DailyMorning_Star/assets/64049788/779847a2-1380-4238-b35f-75cb76050666)

**Comment by Jeremy-stu** [comment]
> GPT是这么理解的
> ![image](https://github.com/JionghaoSong/DailyMorning_Star/assets/64049788/779847a2-1380-4238-b35f-75cb76050666)
> 

测试出来了，是所有的键值字符加起来不能超过200，比如英文每日金句的键值字符数加上 以上的温度、天气之类的键值字符数超过了200，就会导致下面的键值直接省略。（如下图）但还有20个文字的限制，超过20也会省略。例如"abcd efg"算2个文字，8个字符，连续的数字、英文字母被视为一个字
![Screenshot_2023-11-14-10-16-54-805-edit_com.tencent.mm.jpg](https://github.com/JionghaoSong/DailyMorning_Star/assets/76563274/e0c783ac-db0a-469b-8908-0a5d5e547425)

![Screenshot_2023-11-14-10-07-47-104-edit_com.kiwibrowser.browser.jpg](https://github.com/JionghaoSong/DailyMorning_Star/assets/76563274/d5f91d11-245a-41b6-abb3-29530d279433)

**Comment by JionghaoSong** [comment]
可以的，呢这次算是都弄明白了！
