### ISSUE TITLE
已解决 -- 北京时间8点前运行，日期不准

### ISSUE THREAD

**Issue by Jeremy-stu** [JionghaoSong/DailyMorning_Star#18]
没错，又是我，打扰了，如何解决8点前运行得到的时间和星期不准的问题，由于在8点前运行获取到的是国际时间，还在前一天，就导致了不准，有没有好的方法？

**Comment by JionghaoSong** [comment]
可以直接设置时区，你参考https://github.com/szenius/set-timezone

**Comment by JionghaoSong** [comment]
你可以参考参考
name: Example Workflow
on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 00:00执行

env:
  TZ: 'Asia/Shanghai'

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print current time
        run: date

**Comment by Jeremy-stu** [comment]
> 你可以参考参考
> name: Example Workflow
> on:
>   schedule:
>     - cron: '0 0 * * *'  # 每天UTC 00:00执行
> 
> env:
>   TZ: 'Asia/Shanghai'
> 
> jobs:
>   example_job:
>     runs-on: ubuntu-latest
>     steps:
>       - name: Checkout repository
>         uses: actions/checkout@v2
> 
>       - name: Print current time
>         run: date

时区改成上海的话，上面那个运行时间还是按国际时间设置吗？

**Comment by JionghaoSong** [comment]
我感觉写北京时间就行了
但是我看大家在吐槽这个问题 hh，不一定管用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jeremy-stu ***@***.***&gt;
发送时间: 2023年11月14日 14:13
收件人: JionghaoSong/DailyMorning_Star ***@***.***&gt;
抄送: Harry.Song ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [JionghaoSong/DailyMorning_Star] 北京时间8点前运行，日期不准 (Issue #18)

**Comment by Jeremy-stu** [comment]
> 我感觉写北京时间就行了
> 但是我看大家在吐槽这个问题 hh，不一定管用
> 
> 
> 
> 发自我的iPhone
> 
> 
> ------------------ 原始邮件 ------------------
> 发件人: Jeremy-stu ***@***.***&gt;
> 发送时间: 2023年11月14日 14:13
> 收件人: JionghaoSong/DailyMorning_Star ***@***.***&gt;
> 抄送: Harry.Song ***@***.***&gt;, Comment ***@***.***&gt;
> 主题: Re: [JionghaoSong/DailyMorning_Star] 北京时间8点前运行，日期不准 (Issue #18)

![Screenshot_2023-11-14-12-43-24-313-edit_com.github.android.jpg](https://github.com/JionghaoSong/DailyMorning_Star/assets/76563274/d68f3f1e-378c-4909-80a8-dd776d8f72c8)

这样写不知道行不行，明天再看看

**Comment by JionghaoSong** [comment]
嗯 明天看一下日期就知道有没有用了。
其实最稳定的可以挂到自己的服务器上，或者是用gitee

**Comment by Jeremy-stu** [comment]
> 嗯 明天看一下日期就知道有没有用了。
> 其实最稳定的可以挂到自己的服务器上，或者是用gitee

昨天改的有用，日期准了。上面那个运行时间还得按国际标准时间来设置

**Comment by Jeremy-stu** [comment]
> 比如我想北京时间 6点，国际就写 22 对吧。然后自动推过来就是北京时间第二天的？
> 
> 
> 
> 发自我的iPhone
> 
> 
> ------------------ 原始邮件 ------------------
> 发件人: Jeremy-stu ***@***.***&gt;
> 发送时间: 2023年11月15日 11:27
> 收件人: harry.sjh ***@***.***&gt;
> 主题: Re: [JionghaoSong/DailyMorning_Star] 北京时间8点前运行，日期不准 (Issue #18)
> 
> 
> 
> 
> 
>   
> 嗯 明天看一下日期就知道有没有用了。
>  其实最稳定的可以挂到自己的服务器上，或者是用gitee
>   
> 昨天改的有用，日期准了。上面那个运行时间还得按国际标准时间来设置
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

对的

**Comment by Jeremy-stu** [comment]
感觉可以把时区设定的代码加进去，想改推送时间，只用改运行时间就可以了

**Comment by JionghaoSong** [comment]
name: weixin
on:
  workflow_dispatch:
  schedule: 
    # 国际标准时间，北京时间需要+8小时
    # 分别代表 分钟、小时、日期、月份、星期几，没有用*代替。
    # 现在是国际时间的0点01分，也就是北京时间的早上8点01
    - cron: '01 00 * * *'

env:
# 把时区设置为了北京时间，可以规避因为时区问题造成的日期不准确现象
  TZ: 'Asia/Shanghai'
  
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
#           python-version: 3.9.1
      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: weixin
        run: |
          python3 main.py

**Comment by JionghaoSong** [comment]
已更新
