### ISSUE TITLE
没事，已经解决了，谢谢

### ISSUE THREAD

**Issue by linzh227** [JionghaoSong/DailyMorning_Star#20]
获取access_token失败，请检查app_id和app_secret是否正确

**Comment by JionghaoSong** [comment]
你自己检查一下你那几个配置，检查app_id和app_secret是否正确。
这个项目跑了快两年了，目前我自己用是没什么问题的👌(｡•̀ᴗ-)✧

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: linzh227 ***@***.***&gt;
发送时间: 2024年3月21日 15:14
收件人: JionghaoSong/DailyMorning_Star ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [JionghaoSong/DailyMorning_Star] 大哥你好，有bug好像 (Issue #20)





 
获取access_token失败，请检查app_id和app_secret是否正确
