### ISSUE TITLE
我那个项目不是闭源了 是被封了..

### ISSUE THREAD

**Issue by rxrw** [JionghaoSong/DailyMorning_Star#3]

**Comment by JionghaoSong** [comment]
OK 那我改一下。
我记着没封之前，是不是还上了trending，蛮可惜的。

**Comment by rxrw** [comment]
> OK 那我改一下。
> 我记着没封之前，是不是还上了trending，蛮可惜的。

没事我就是突然怀念一下搜索搜索

对 大量占用人家服务器 被封了 trending 第一有点可怕

**Comment by doha307** [comment]
#`
![Uploading FB_IMG_1675250496374.jpg…]()
`
